name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código desde GitHub
        uses: actions/checkout@v3

      - name: Actualizar código en EC2
        run: |
          cd ~/repo_backup
          git reset --hard
          git pull origin main
          rsync -av --delete ~/repo_backup/ /var/www/html/
          sudo systemctl restart apache2
