name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy_wd:
    runs-on: wd

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update code on EC2
        run: |
          cd ~/repo_backup
          git pull origin main
          sudo cp -r ~/repo_backup/* /var/www/html/
          sudo systemctl restart apache2
          
  deploy_delgado:
    runs-on: delgado

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update code on EC2
        run: |
          cd ~/repo_backup
          git pull origin main
          sudo cp -r ~/repo_backup/* /var/www/html/
          sudo systemctl restart apache2          
  
  deploy_dyland:
    runs-on: dyland

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update code on EC2
        run: |
          cd ~/repo_backup
          git pull origin main
          sudo cp -r ~/repo_backup/* /var/www/html/
          sudo systemctl restart apache2          
          
  deploy_juanl:
    runs-on: juanl

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update code on EC2
        run: |
          cd ~/repo_backup
          git pull origin main
          sudo cp -r ~/repo_backup/* /var/www/html/
          sudo systemctl restart apache2
